import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/LegalPage";

export const metadata: Metadata = { title: "Safeguarding & Emergency Information | Rebecca Lauren Coaching", description: "Safeguarding, urgent support and work with young people at Rebecca Lauren Coaching." };

export default function Safeguarding() {
  return <LegalPage eyebrow="Safety comes first" title="Safeguarding & Emergency Information" intro="How safety, urgent concerns and work with young people are approached." sections={[
    { heading: "Emergency and urgent support", content: <><p><strong>Rebecca Lauren Coaching is not an emergency or crisis service and messages are not monitored continuously.</strong> Do not use the enquiry form, email, WhatsApp or a future appointment when urgent help is needed.</p><ul><li>Call <strong>999</strong> or go to A&amp;E if there is immediate danger or a life-threatening emergency.</li><li>In England, call <strong>NHS 111</strong> and select the mental-health option for urgent mental-health support.</li><li>Call Samaritans free on <strong>116 123</strong>, day or night, for confidential emotional support.</li></ul><p>If you are outside England, use the urgent-health or emergency service for your location.</p></> },
    { heading: "Our safeguarding approach", content: <><p>Rebecca aims to work in a way that promotes welfare, listens to the person receiving support and responds proportionately to concerns. The welfare and best interests of a child are a primary consideration. Safeguarding is a shared responsibility and coaching does not replace the duties of parents, schools, healthcare services, social care or the police.</p><p>This approach is informed by current statutory safeguarding guidance for England. Rebecca will seek additional professional or safeguarding advice when a concern is outside her role or competence.</p></> },
    { heading: "Confidentiality and information sharing", content: <><p>Coaching is intended to be private, but confidentiality is not absolute. If Rebecca reasonably believes a child, young person, adult at risk, client or another person is at risk of abuse, neglect or serious harm, relevant information may be shared with an appropriate person or service.</p><p>Depending on the concern, this may include a parent or guardian, designated safeguarding lead, healthcare professional, local authority children&apos;s or adult social care, police or emergency services. Consent will normally be sought where it is safe and appropriate, but a concern may be shared without consent when necessary and lawful. The aim is to share only information that is relevant, accurate and proportionate.</p></> },
    { heading: "Working with children and young people", content: <><p>A parent or legal guardian must make the initial enquiry for anyone under 18. Before coaching begins, Rebecca will agree suitable consent, contact, privacy, emergency and guardian-involvement arrangements. The young person should receive an age-appropriate explanation of coaching and the limits of confidentiality.</p><p>Their wishes and feelings will be heard, while recognising that adults may need to act to keep them safe. Rebecca may decline, pause or end coaching and recommend specialist or statutory support if the arrangement is not suitable or a risk cannot be managed safely.</p></> },
    { heading: "Online and telephone safety", content: <><p>Remote sessions should take place in an appropriate, private and physically safe setting. At the outset, Rebecca may confirm the client&apos;s location, a guardian or emergency contact and what to do if the connection fails or a safety concern arises.</p><p>Rebecca may pause or end a session if identity, privacy, supervision or safety cannot be maintained. Online coaching must not take place while the client is driving or undertaking another hazardous activity.</p></> },
    { heading: "If a concern arises", content: <><p>Rebecca will listen, avoid promising secrecy, record relevant facts, consider immediate safety and seek or make an appropriate safeguarding referral where needed. She will not investigate an allegation herself or confront an alleged person in a way that could increase risk.</p><p>If your concern is about Rebecca&apos;s conduct, do not wait for Rebecca to investigate it. Contact the relevant local authority children&apos;s or adult safeguarding service, the police, or emergency services according to the seriousness and urgency. A concern involving work with a child may also be referred to the local authority designated officer (LADO).</p></> },
    { heading: "What to include in a non-urgent message", content: <><p>For a general or non-urgent enquiry, share only enough information for Rebecca to respond. Do not send detailed disclosures, medical records or evidence through the website. If a disclosure or urgent concern is already known, contact the appropriate safeguarding, health or emergency service directly.</p><p>For information about how personal information is handled, read the <Link href="/privacy">Privacy Policy</Link>. For the limits of coaching, read the <Link href="/disclaimer">Coaching Disclaimer</Link>.</p></> },
  ]} />;
}
