import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { CertificateGallery } from "@/components/CertificateGallery";
import { CTA, SectionHeading, TestimonialCards } from "@/components/Shared";

export const metadata: Metadata = { title: "About Rebecca | Rebecca Lauren Coaching", description: "Meet Rebecca, a warm and compassionate Mental Health Coach and Advocate offering personalised online support.", alternates: { canonical: "/about" } };

export default function AboutPage() {
  return <main>
    <section className="page-hero about-hero"><div className="container page-hero-grid"><div><p className="eyebrow">The heart behind the work</p><h1>Meet Rebecca</h1><p className="page-subtitle">Mental Health Coach and Advocate</p><p className="hero-lede">A warm, understanding and practical approach shaped by both professional learning and lived experience.</p><Link className="button" href="/contact">Talk with Rebecca <span>→</span></Link></div><div className="about-photo"><Image src="/images/rebecca-coaching.jpg" alt="Rebecca enjoying a peaceful moment in nature" fill priority sizes="(max-width: 800px) 90vw, 42vw" /><span className="photo-caption">A quiet moment in nature ♡</span></div></div></section>

    <section className="section"><div className="container story-grid"><div><p className="eyebrow">A little about me</p><h2>Hi, I’m Rebecca.</h2><p className="lead-serif">I’m passionate about helping adults, children, teenagers and families feel calmer, more confident, understood and empowered.</p></div><div><p>My approach is warm, compassionate and practical. I believe everyone deserves a safe space where they can talk openly, feel heard and explore support without judgement.</p><p>I meet each person where they are, taking time to understand what feels difficult and what meaningful progress looks like for them.</p></div></div></section>

    <section className="section journey"><div className="container journey-grid"><div className="journey-card"><p className="eyebrow">My journey</p><h2>Why this work<br /><em>matters to me</em></h2><p>I was diagnosed with Fibromyalgia and ADHD only a few years ago. Receiving my diagnosis helped so many parts of my life finally make sense.</p><p>That personal journey has given me a deep understanding of how isolating and overwhelming challenges can feel. I want every person I work with to know that they do not have to face things alone.</p><p>With the right support, it is possible to understand your needs, embrace your differences, develop helpful strategies and move forward with greater confidence.</p></div><div className="journey-image"><Image src="/images/meet-rebecca.webp" alt="Portrait of Rebecca with soft floral details" fill sizes="(max-width: 800px) 90vw, 45vw" /></div></div></section>

    <section className="section family-section"><div className="container family-grid"><div className="family-art"><Image src="/images/anxiety-adhd-coaching.webp" alt="Illustration representing calm online coaching support" fill sizes="(max-width: 800px) 90vw, 40vw" /></div><div><p className="eyebrow">Supporting together</p><h2>Families flourish with <em>understanding.</em></h2><p>Supporting a child or teenager is often a team effort. I work collaboratively with parents and caregivers, offering guidance and practical tools that can help create greater consistency, understanding and calm at home.</p><Link className="text-link" href="/services">Explore family support <span>→</span></Link></div></div></section>

    <section className="section values-section"><div className="container"><SectionHeading eyebrow="What guides my work" title="My values" /><div className="values-grid">{[["Compassion", "Care that begins with listening."], ["Understanding", "A space to feel truly heard."], ["Individuality", "Support that honours your needs."], ["Empowerment", "Tools that build self-belief."], ["Non-judgement", "A warm, accepting relationship."]].map(([title, copy], i) => <article key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>

    <section className="section certificates-section"><div className="container"><SectionHeading eyebrow="Qualifications" title="Training and professional development" copy="Ongoing learning helps me offer informed, thoughtful and responsible coaching support." /><CertificateGallery /></div></section>

    <section className="section fun-section"><div className="container"><SectionHeading eyebrow="Away from coaching" title="A few things about me" /><div className="fun-grid">{[["☕", "Coffee", "Coffee always helps."], ["♡", "Animals", "I do not currently have pets, but I love all animals."], ["⌇", "Favourite book", "Rebecca by Daphne du Maurier."], ["❀", "Self-care", "Shopping trips and peaceful nature walks."]].map(([icon, title, copy]) => <article key={title}><span>{icon}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></div></section>

    <section className="section testimonials-section" id="testimonials"><div className="container"><SectionHeading eyebrow="Client and family feedback" title="Experiences shared with kindness" /><TestimonialCards /><p className="testimonial-note">Testimonials reflect individual experiences and do not guarantee specific outcomes.</p><div className="personal-feedback"><p className="eyebrow">Personal character feedback</p><blockquote>“I have known Rebecca for many years. She has been a constant source of comfort, support and encouragement — unfailingly kind and compassionate.”</blockquote><p>This reflects a personal relationship and is shared as character feedback, not as a clinical or coaching outcome.</p></div></div></section>
    <CTA title="Ready to talk?" copy="You’re welcome to ask questions and explore whether coaching feels right for you or your family." button="Contact Rebecca" />
  </main>;
}
