import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/LegalPage";

export const metadata: Metadata = { title: "Privacy Policy | Rebecca Lauren Coaching", description: "How Rebecca Lauren Coaching handles personal information." };

export default function Privacy() {
  return <LegalPage eyebrow="Your information" title="Privacy Policy" intro="How information shared with Rebecca Lauren Coaching is handled." sections={[
    { heading: "Who is responsible for your information", content: <><p>Rebecca Lauren Shaw, trading as Rebecca Lauren Coaching, is the controller of personal information handled for enquiries and coaching services. Questions or requests can be sent to <a href="mailto:rebeccalauren875@gmail.com">rebeccalauren875@gmail.com</a>.</p><p>This policy applies to this website and direct communications with Rebecca. Separate providers such as WhatsApp, Instagram and your email provider also process information under their own privacy policies.</p></> },
    { heading: "Information we may collect", content: <><p>When you contact Rebecca, we may receive your name, email address, telephone number, preferred contact method, who support is for, age range, broad support area, preferred session format and the message you choose to send. If coaching begins, we may also keep booking, consent, payment, correspondence and proportionate coaching notes.</p><p>Please share only what is needed to begin the conversation. Do not send detailed medical histories, identity documents or highly sensitive information through the website.</p></> },
    { heading: "How the website enquiry works", content: <><p>The website form prepares an email or WhatsApp message using the information you enter. You can review it in your chosen app before sending. The form is not intended to create a separate online client database.</p><p>Website hosting and security services may receive limited technical information such as IP address, device or browser details, requested pages, timestamps and security logs when you use the site.</p></> },
    { heading: "How and why we use information", content: <><p>Information is used to respond to enquiries, assess whether coaching may be suitable, arrange consultations and sessions, deliver and administer agreed services, keep appropriate records, protect the website, comply with legal or insurance obligations, and respond to safeguarding or serious safety concerns.</p><p>We do not sell personal information, use it for unrelated advertising, or make automated decisions or profiles that have legal or similarly significant effects.</p></> },
    { heading: "Our lawful bases", content: <><p>Depending on the circumstances, processing is necessary to take steps at your request before a coaching contract, to perform a contract, or for legitimate interests in responding to enquiries, administering a safe service and securing the website. Those interests are balanced against your rights, with particular care for children.</p><p>We may also process information to meet a legal obligation, to protect someone&apos;s vital interests, or where safeguarding law permits or requires it. Where special-category information is relevant, we rely on an additional lawful condition, which may include explicit consent or substantial public-interest safeguarding conditions. Consent can be withdrawn, but this does not affect earlier lawful processing.</p></> },
    { heading: "Children and young people", content: <><p>A parent or legal guardian should make the initial enquiry for anyone under 18. We aim to use clear, age-appropriate explanations, collect only what is necessary, respect the young person&apos;s data rights and make their welfare and best interests a primary consideration.</p><p>Parental involvement does not remove a young person&apos;s own privacy rights. Information may nevertheless be shared without consent when this is lawful and necessary to address a safeguarding concern or serious risk.</p></> },
    { heading: "Who information may be shared with", content: <><p>Information is shared only where necessary with service providers supporting email, communications, website hosting, security, professional administration or payment arrangements. If you choose WhatsApp or Instagram, information is also handled by those platforms.</p><p>Where lawful and necessary, relevant information may be shared with a parent or guardian, healthcare professional, school safeguarding lead, local authority children&apos;s or adult social care, police, emergency service, insurer, legal adviser or regulator. We aim to share the minimum information needed.</p><p>Some technology providers may process information outside the UK. Where Rebecca selects a processor, appropriate contractual or other lawful transfer safeguards should be used. Third-party platforms are also responsible for explaining their own international processing.</p></> },
    { heading: "Security and retention", content: <><p>Reasonable organisational and technical measures are used to protect information, but no email, messaging platform or internet service can be guaranteed completely secure. Please avoid sending unnecessary sensitive details.</p><p>General enquiries that do not lead to coaching are ordinarily kept for no longer than 12 months after the last meaningful contact. If coaching begins, records are kept only for as long as reasonably needed for the service and applicable legal, tax, insurance, complaints and safeguarding responsibilities, then securely deleted or anonymised. A safeguarding or legal hold may require longer retention.</p></> },
    { heading: "Cookies and technical data", content: <><p>This website does not intentionally use advertising or behavioural-profiling cookies. The hosting provider may process essential technical logs or use security technology needed to deliver and protect the site. If optional analytics or marketing cookies are introduced, this policy and any consent controls will be updated first.</p></> },
    { heading: "Your data-protection rights", content: <><p>Depending on the circumstances, you may ask for access to your personal information, correction, erasure, restriction, objection, or transfer of information you supplied. You may withdraw consent at any time where consent is the basis used. Some rights have legal exceptions, including safeguarding and record-keeping duties.</p><p>Send a request to <a href="mailto:rebeccalauren875@gmail.com">rebeccalauren875@gmail.com</a>. We may need to confirm identity and normally respond within one month. If you are unhappy, please contact Rebecca first. You can also complain to the UK Information Commissioner&apos;s Office at <a href="https://ico.org.uk/make-a-complaint/" target="_blank" rel="noreferrer">ico.org.uk/make-a-complaint</a>.</p></> },
    { heading: "Changes to this policy", content: <><p>This policy will be reviewed when the website, services or information practices change. The date at the top identifies the current version. Material changes will be explained on the website where appropriate.</p><p>For safeguarding limits on privacy, please also read <Link href="/safeguarding">Safeguarding &amp; Emergency Information</Link>.</p></> },
  ]} />;
}
