import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/LegalPage";

export const metadata: Metadata = { title: "Website Terms | Rebecca Lauren Coaching", description: "Terms governing the use of the Rebecca Lauren Coaching website." };

export default function Terms() {
  return <LegalPage eyebrow="Using this website" title="Website Terms" intro="Important information about the content and use of this website." sections={[
    { heading: "Who we are", content: <><p>This website is operated by Rebecca Lauren Shaw, trading as Rebecca Lauren Coaching (“Rebecca”, “we”, “us” or “our”). You can contact Rebecca at <a href="mailto:rebeccalauren875@gmail.com">rebeccalauren875@gmail.com</a> or through the <Link href="/contact">contact page</Link>.</p><p>These terms apply when you browse or use this website. They do not replace the separate service agreement, fees, cancellation arrangements and consent information supplied before coaching begins.</p></> },
    { heading: "Information, not individual advice", content: <><p>The website explains Rebecca&apos;s coaching services and provides general wellbeing information. It is not personalised medical, psychological, therapeutic, legal or safeguarding advice, and must not be relied upon as a diagnosis or treatment recommendation.</p><p>Rebecca Lauren Coaching is not an emergency or crisis service. Please read the <Link href="/disclaimer">Coaching Disclaimer</Link> and <Link href="/safeguarding">Safeguarding &amp; Emergency Information</Link> before making an enquiry.</p></> },
    { heading: "Enquiries, consultations and bookings", content: <><p>Sending an enquiry or attending a free discovery consultation does not create a coaching relationship or confirm a booking. A consultation is an opportunity to discuss goals, comfort and possible suitability; it does not guarantee that coaching will be offered or produce a particular result.</p><p>Availability, suitability, session format, fees, payment and cancellation terms will be confirmed directly. Any consumer rights provided by law remain unaffected.</p></> },
    { heading: "Qualifications and service descriptions", content: <><p>Reasonable care is taken to describe Rebecca&apos;s training and services accurately. Certificates displayed on the website evidence completion or achievement stated on each certificate. They do not imply medical registration, statutory regulation or a regulated qualification unless expressly stated.</p><p>For clarity, the OCN London infant sleep consultancy Record of Achievement confirms completion of an accredited and assessed Level Three course; the certificate states that it does not form part of an OCN London regulated qualification.</p></> },
    { heading: "Acceptable use", content: <><p>You must not misuse the website, attempt unauthorised access, introduce malicious code, interfere with its operation, submit false or unlawful material, impersonate another person, or use its content in a way that infringes another person&apos;s rights.</p><p>The enquiry form must not be used for emergencies, abuse, spam or highly detailed medical records. A parent or legal guardian should make the initial enquiry for anyone under 18.</p></> },
    { heading: "Intellectual property", content: <><p>Unless stated otherwise, the website&apos;s original text, branding, layout and design are owned by or licensed to Rebecca Lauren Coaching. You may view and print a reasonable copy for personal, non-commercial use. You may not reproduce, alter, sell or commercially exploit website material without prior written permission.</p><p>Third-party names, logos, certificates and images remain the property of their respective owners.</p></> },
    { heading: "Availability, accuracy and external links", content: <><p>We aim to keep the website accurate, secure and available, but do not promise uninterrupted or error-free access. Content, services and availability may change, and the website may be suspended for maintenance or security reasons.</p><p>Links to email, WhatsApp, Instagram, NHS, government or other third-party services are provided for convenience. Those services operate under their own terms and privacy policies, and we are not responsible for their content or availability.</p></> },
    { heading: "Liability and your statutory rights", content: <><p>Nothing in these terms excludes or limits liability where it would be unlawful to do so, including liability for death or personal injury caused by negligence, fraud or fraudulent misrepresentation. Nothing affects rights you have under consumer law.</p><p>Subject to those protections, we are not responsible for losses caused by relying on general website content as individual advice, by events outside our reasonable control, or by third-party websites and services. If you are using this website for business purposes, we are not liable for loss of profit, business, opportunity or data to the extent permitted by law.</p></> },
    { heading: "Changes and governing law", content: <><p>We may update these terms when the website, services or law changes. The date at the top shows the latest version. Continued use after an update means the revised terms apply from that point.</p><p>These terms are governed by the law of England and Wales. If you are a consumer living elsewhere in the United Kingdom, you retain any mandatory protections and rights to bring proceedings available in the part of the UK where you live.</p></> },
  ]} />;
}
