import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/components/LegalPage";

export const metadata: Metadata = { title: "Coaching Disclaimer | Rebecca Lauren Coaching", description: "The scope and limits of Rebecca Lauren Coaching services." };

export default function Disclaimer() {
  return <LegalPage eyebrow="Please read" title="Coaching Disclaimer" intro="Understanding the scope and limits of coaching support." sections={[
    { heading: "The nature of coaching", content: <><p>Coaching is a collaborative, non-clinical service. It can support reflection, practical strategies, confidence, self-understanding, routines and everyday goals. It is educational and supportive rather than diagnostic or curative.</p><p>Coaching is not psychotherapy, counselling, psychiatry, medical care, diagnosis, treatment, social work, crisis intervention or a substitute for any regulated professional service.</p></> },
    { heading: "Medical and mental-health care", content: <><p>Do not delay or discontinue advice, medication or treatment from a GP, psychiatrist, psychologist, therapist or other qualified professional because of information on this website or a coaching conversation. Questions about symptoms, diagnosis, medication, treatment or risk should be taken to an appropriately qualified healthcare professional.</p><p>Rebecca may pause or decline coaching and suggest another service when needs fall outside coaching scope. This is not a clinical assessment or referral guarantee.</p></> },
    { heading: "Your choices and responsibility", content: <><p>You decide whether and how to use ideas discussed in coaching. You remain responsible for your choices, actions, wellbeing and for seeking specialist help when needed. Please tell Rebecca if an activity feels unsuitable or if circumstances change.</p><p>No specific improvement, timescale or outcome is promised or guaranteed. Results vary according to individual circumstances, participation and factors beyond Rebecca&apos;s control.</p></> },
    { heading: "Children and young people", content: <><p>A parent or legal guardian must make the initial enquiry for a person under 18 and provide appropriate consent and involvement before coaching begins. Arrangements will be age-appropriate, child-centred and agreed with the family, while listening to the young person&apos;s wishes and feelings.</p><p>Coaching does not replace a school&apos;s, parent&apos;s, healthcare provider&apos;s or local authority&apos;s responsibilities. Rebecca may recommend that a parent contacts one of those services.</p></> },
    { heading: "Confidentiality has limits", content: <><p>Rebecca aims to treat coaching conversations respectfully and privately. Confidentiality cannot be absolute. Information may be shared when required by law or when Rebecca reasonably believes this is necessary to protect a child, an adult at risk, the client or another person from serious harm.</p><p>Only relevant information should be shared, and the client or guardian will usually be told where it is safe and appropriate to do so. See the <Link href="/safeguarding">Safeguarding &amp; Emergency Information</Link> and <Link href="/privacy">Privacy Policy</Link>.</p></> },
    { heading: "Online and telephone sessions", content: <><p>For remote sessions, the client should choose a private, safe place and use a suitable device and connection. Sessions must not take place while driving or doing anything requiring full attention. Technical problems may require a session to be rearranged.</p><p>Rebecca may pause or end a session if privacy, identity, safety or the ability to communicate cannot be maintained.</p></> },
    { heading: "Not an emergency service", content: <><p>Rebecca Lauren Coaching does not provide continuous monitoring, urgent response or crisis care. Do not wait for a reply to an email, form or WhatsApp message if anyone may be in immediate danger.</p><p>Call <strong>999</strong> or go to A&amp;E for an immediate or life-threatening emergency. In England, call <strong>NHS 111</strong> and select the mental-health option for urgent mental-health support. Samaritans can be contacted free, day or night, on <strong>116 123</strong>.</p></> },
  ]} />;
}
